name: hello-world
on: push
jobs:
        my-job:
                runs-on: ubuntu-latesst
                steps:
                        - name: my-step
                          run: echo "Hello World!"
